# Generated by Django 2.1.5 on 2020-12-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201231_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for Delivery', 'Out for Delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Outdoor', 'Outdoor'), ('Indoor', 'Indoor')], max_length=200, null=True),
        ),
    ]
