# Generated by Django 2.1.5 on 2021-01-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to=''),
        ),
    ]
